# Generated by Django 5.2.1 on 2025-05-19 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDog',
            fields=[
                ('DogID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Dog_Name', models.CharField(max_length=50)),
                ('Dog_type', models.CharField(choices=[('dog_with_owner', 'Dog with Owner'), ('stray_dog', 'Stray Dog')], max_length=20)),
                ('Breed', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Image', models.ImageField(blank=True, default='default.png', null=True, upload_to='dogs/')),
                ('Description', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
