# Generated by Django 5.2.1 on 2025-05-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dog_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dogID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
