# Generated by Django 5.2.1 on 2025-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dog_dogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dogID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
