# Generated by Django 5.2.1 on 2025-05-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dog_dogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='ownerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='ownerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='ownerPhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
